Update Dockerfile, replace coc.vim with lsp.vim and autocomplete.vim
This commit updates the Dockerfile to add python3.10-venv and to include
git configurations in a more conventional format.
It removes the installation of languageserver for R and specifies
nerdfonts for NERDTreeGitStatus in vim.
The coc-settings.json and coc.vim files used for coc.nvim have been
removed, with the coc.nvim plugin also being removed from plugins.vim.
Instead, lsp.vim and autocomplete.vim are introduced to be sourced in
vimrc for language server protocol and autocompletion setup.
.vim/config/coc.vim is being replaced with .vim/config/lsp.vim and
.vim/config/autocomplete.vim for better language server support.
Moreover, 'utf-8' encoding is set in vim.vim.
The vim/coc-settings.json file was deleted, new files
vim/config/autocomplete.vim and vim/config/lsp.vim were created.
Build script was also updated to comment out automatic Docker login and
image push.
Lastly, nerdtree-git-plugin settings have been adjusted to utilize
nerdfonts.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,20 +1,20 @@
 username="fonzzy1"
 
 # Prompt for Docker password
-read -s -p "Enter Docker password for user $username: " DOCKER_PASSWORD
+#read -s -p "Enter Docker password for user $username: " DOCKER_PASSWORD
 
 # Login to Docker Hub
-echo "$DOCKER_PASSWORD" | docker login -u "$username" --password-stdin
+#echo "$DOCKER_PASSWORD" | docker login -u "$username" --password-stdin
 
 # Build Docker Images
 docker build . -t "${username}/vim"
 
 
 # Make sure the login was successful before pushing images
-if [ $? -eq 0 ]; then
-    # Push Docker Images to Docker Hub
-    docker push "${username}/vim"
-else
-    echo "Docker login failed. Cannot push images."
-    exit 1
-fi
+#if [ $? -eq 0 ]; then
+#    # Push Docker Images to Docker Hub
+#    docker push "${username}/vim"
+#else
+#    echo "Docker login failed. Cannot push images."
+#    exit 1
+#fi
