Enable Docker image pushing and refine markdown functions
The docker image pushing code has been uncommented thus enabling functionality to push Docker Images to Docker Hub after successful login.
Added a CreateMdFile function which creates a new markdown file, with the filename generated from the current file.
Moreover, the `quarto preview` and `quarto render` functions have been refined to handle filepaths with spaces correctly by enclosing the file path in quotation marks.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -11,10 +11,10 @@ docker build . -t "${username}/vim"
 
 
 # Make sure the login was successful before pushing images
-#if [ $? -eq 0 ]; then
-#    # Push Docker Images to Docker Hub
-#    docker push "${username}/vim"
-#else
-#    echo "Docker login failed. Cannot push images."
-#    exit 1
-#fi
+if [ $? -eq 0 ]; then
+    # Push Docker Images to Docker Hub
+    docker push "${username}/vim"
+else
+    echo "Docker login failed. Cannot push images."
+    exit 1
+fi
